name: sra1-app

on:
  push:
    branches: [main]

env:
  AZURE_CONTAINER_REGISTRY: sravanaksregistry
  CONTAINER_NAME: myapp
  CLUSTER_NAME: sravan-aks
  CLUSTER_RESOURCE_GROUP: sravan-aks-rg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name $AZURE_CONTAINER_REGISTRY

      - name: Build Image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY.azurecr.io/$CONTAINER_NAME:${{ github.sha }} .

      - name: Push Image
        run: |
          docker push $AZURE_CONTAINER_REGISTRY.azurecr.io/$CONTAINER_NAME:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group $CLUSTER_RESOURCE_GROUP \
            --name $CLUSTER_NAME

      - name: Deploy to AKS
        run: |
          kubectl create deployment myapp \
            --image=$AZURE_CONTAINER_REGISTRY.azurecr.io/$CONTAINER_NAME:${{ github.sha }} \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl expose deployment myapp \
            --type=LoadBalancer \
            --port=80 \
            --target-port=5000 \
            --dry-run=client -o yaml | kubectl apply -f -
